import { EProjectType, IProject } from "@/types";

export const projectGroups: IProject[] = [
  {
    type: EProjectType.OPEN_APP,
    items: [
      {
        title: "Wordle with Friends",
        description: "Multiplayer version of trending Wordle game",
        duration: "2022",
        link: "https://github.com/dgvai/wordle-with-friends/",
        image: "https://repository-images.githubusercontent.com/457659481/659c23b3-a101-4f75-84ed-5bb5f0547868",
        tags: ["ReactJS", "Tailwind", "Firebase"],
      },
      {
        title: "Pitch Tuner - WebAudio API",
        description: "Guitar tuner, uses auto-correlation algorithm",
        duration: "2021",
        link: "https://github.com/dgvai/webaudio-pitch-tuner/",
        image: "https://repository-images.githubusercontent.com/389949001/8a8ab236-fbc3-4252-8210-dbad7397a2eb",
        tags: ["ReactJS", "Tailwind"],
      },
    ],
  },
  {
    type: EProjectType.OPEN_LIB,
    items: [
      {
        title: "Maccy Menu",
        description: "GNOME Shell Extension for Debian Distro (Linux)",
        duration: "2023",
        link: "https://extensions.gnome.org/extension/6021/maccy-menu/",
        image: "https://repository-images.githubusercontent.com/650221439/eaae718a-f3d7-4a09-89ba-eb2d596def46",
        tags: ["JavaScript", "GNOME", "Gtk", "Debian"],
      },
      {
        title: "Laravel AdminLTE Components",
        description: "Laravel Blade components for AdminLTE UI Kit",
        duration: "2020",
        link: "https://github.com/dgvai/laravel-adminlte-components",
        image: "https://repository-images.githubusercontent.com/263046930/eed75300-95f0-11ea-9006-18223465873d",
        tags: ["Laravel", "PHP", "Blade"],
      },
      {
        title: "Laravel SSLCommerz",
        description: "Payment gateway wrapper library for Laravel",
        duration: "2020",
        link: "https://github.com/dgvai/laravel-sslcommerz",
        image: "https://repository-images.githubusercontent.com/255674859/f4b41880-7f0c-11ea-8c16-3ecad35b7bbc",
        tags: ["Laravel", "PHP", "Payment Gateway"],
      },
      {
        title: "Laravel Nagad",
        description: "Payment gateway wrapper library for Laravel",
        duration: "2020",
        link: "https://github.com/dgvai/laravel-nagad",
        image: "https://repository-images.githubusercontent.com/297919060/780d293a-da7b-4b98-ad98-ecd0e90151ed",
        tags: ["Laravel", "PHP", "Payment Gateway"],
      },
      {
        title: "Laravel User Review",
        description: "Trait for Laravel Eloquent Modell",
        duration: "2020",
        link: "https://github.com/dgvai/laravel-user-review",
        image: "https://repository-images.githubusercontent.com/249742172/08ac4a00-7f0e-11ea-83c0-a7a26627768f",
        tags: ["Laravel", "PHP"],
      },
      {
        title: "Laravel OnnorokomSMS",
        description: "Notification Channel Plugin for Laravel",
        duration: "2020",
        link: "https://github.com/dgvai/laravel-notification-channel-onnorokomsms",
        image: "https://repository-images.githubusercontent.com/255384700/e0245000-7f0d-11ea-87a3-61b6dfa08224",
        tags: ["Laravel", "PHP", "notification-channel"],
      },
      {
        title: "Laravel i-SMS",
        description: "Notification Channel Plugin for Laravel",
        duration: "2020",
        link: "https://github.com/dgvai/laravel-notification-channel-isms",
        image: "https://repository-images.githubusercontent.com/270543354/1d8ee200-a981-11ea-9ae1-d87f37d30d87",
        tags: ["Laravel", "PHP", "notification-channel"],
      },
      {
        title: "Laravel Invoicer",
        description: "Invoice generator library for Laravel",
        duration: "2020",
        link: "https://github.com/dgvai/laravel-invoicer",
        image: "https://repository-images.githubusercontent.com/255977553/0973c900-7f6c-11ea-8842-bbb75ea48bd4",
        tags: ["Laravel", "PHP"],
      },
      {
        title: "Lartaller",
        description: "Laravel application installer library for production",
        duration: "2020",
        link: "https://github.com/dgvai/larataller",
        image: "https://repository-images.githubusercontent.com/260679571/a1322080-8ca9-11ea-85f0-034c641260d9",
        tags: ["Laravel", "PHP"],
      },
      {
        title: "Demo Mode",
        description: "A library to provide demo mode access in production",
        duration: "2020",
        link: "https://github.com/dgvai/laravel-demo-mode",
        image: "https://repository-images.githubusercontent.com/266292525/6e57d700-9d01-11ea-93b7-f50a1cdb1f55",
        tags: ["Laravel", "PHP"],
      },
    ],
  },
  {
    type: EProjectType.PVT_REPO,
    items: [
      {
        title: "Ganz",
        description: "Shipment Management Software",
        duration: "2021",
        link: "#",
        image: "https://i.ibb.co/4t8xQrv/ganz.png",
        tags: ["Laravel", "PHP", "VueJS"],
      },
      {
        title: "EcomCMS",
        description: "e-Commerce Content Management System",
        duration: "2020",
        link: "#",
        image: "https://i.ibb.co/R9B87Ln/ecomcms.png",
        tags: ["Laravel", "PHP", "VueJS"],
      },
      {
        title: "Portify",
        description: "Portfolio Content Management System",
        duration: "2020",
        link: "#",
        image: "https://i.ibb.co/wrZSvLQ/portify.png",
        tags: ["Laravel", "PHP", "ReactJS"],
      },
      {
        title: "TeamCMS",
        description: "Organizational Team Management System",
        duration: "2019",
        link: "#",
        image: "https://i.ibb.co/86GWwhR/teamCMS.png",
        tags: ["Laravel", "PHP", "Blade"],
      },
    ],
  },
];
